[workspace]
resolver = "3"
members = ["desktop", "fs", "gfx", "kernel", "mem", "net", "relay", "sync", "task", "tls", "xtask"]
# El kernel solo compila para x86_64-unknown-none (lo hace `cargo xtask`). Sin esto,
# `cargo test` o `cargo build` a secas intentarían compilarlo para Windows/Linux y fallarían.
default-members = ["desktop", "fs", "gfx", "mem", "net", "relay", "sync", "task", "tls", "xtask"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
undocumented_unsafe_blocks = "deny"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = 1
